[package]
name = "QM_Programm"
version = "0.1.0"
edition = "2021" # Rust edition to use

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
